services:
  bruker-postgres:
    image: postgres:15
    container_name: bruker-postgres
    restart: always
    environment:
      POSTGRES_USER: bruker
      POSTGRES_PASSWORD: bruker
      POSTGRES_DB: bruker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bruker-backend:
    build:
      context: ./bruker_backend
      dockerfile: .docker/Dockerfile
    container_name: bruker-backend
    volumes:
      - ./bruker_backend:/app
    ports:
      - "8000:8000"
    env_file:
      - bruker_backend/.env
    depends_on:
      - bruker-postgres

  bruker-frontend:
    build:
      context: ./bruker_frontend
      dockerfile: .docker/Dockerfile
    container_name: bruker-frontend
    volumes:
      - ./bruker_frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - bruker-backend

  bruker-nginx:
    image: nginx:alpine
    container_name: bruker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - bruker-backend
      - bruker-frontend

volumes:
  postgres_data: