services:
  bruker-postgres:
    image: postgres:15
    container_name: bruker-postgres
    restart: always
    environment:
      POSTGRES_USER: bruker
      POSTGRES_PASSWORD: bruker
      POSTGRES_DB: bruker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bruker-pgadmin:
    image: dpage/pgadmin4
    container_name: bruker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bruker.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - bruker-postgres

  bruker-backend:
    build:
      context: ./bruker_backend
      dockerfile: .docker/Dockerfile
    container_name: bruker-backend
    volumes:
      - ./bruker_backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=bruker_backend.settings
      - WATCHMAN_STORAGE_PATH=/tmp
    env_file:
      - bruker_backend/.env
    depends_on:
      - bruker-postgres

  bruker-frontend:
    build:
      context: ./bruker_frontend
      dockerfile: .docker/Dockerfile
    container_name: bruker-frontend
    volumes:
      - ./bruker_frontend/src:/app/src
      - ./bruker_frontend/.env:/app/.env
      - ./bruker_frontend/index.html:/app/index.html
      - ./bruker_frontend/package.json:/app/package.json
      - ./bruker_frontend/tsconfig.app.json:/app/tsconfig.app.json
      - ./bruker_frontend/tsconfig.node.json:/app/tsconfig.node.json
      - ./bruker_frontend/tsconfig.json:/app/tsconfig.json
      - ./bruker_frontend/vite.config.ts:/app/vite.config.ts
    ports:
      - "5173:5173"
    depends_on:
      - bruker-backend

volumes:
  postgres_data:
