services:
  bruker-backend:
    build:
      context: ./bruker_backend
      dockerfile: .docker/Dockerfile
    container_name: bruker-backend-dev
    volumes:
      - ./bruker_backend:/app
    ports:
      - "8000:8000"
    env_file:
      - bruker_backend/.env

  bruker-frontend:
    build:
      context: ./bruker_frontend
      dockerfile: .docker/Dockerfile
    container_name: bruker-frontend-dev
    volumes:
      - ./bruker_frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - bruker-backend

  bruker-nginx:
    image: nginx:alpine
    container_name: bruker-nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - bruker-backend
      - bruker-frontend
