name: Update Submodules via Cron

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure git for commit
        run: |
          git config user.name "Github Actions"
          git config user.email "github-actions@users.noreply.github.com"

      - name: Update submodules to latest commits
        run: |
          git submodule update --remote --merge

      - name: Check if there are any changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes if any
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git add .
          git commit -m "[Github Actions] Update submodules"
          git push origin main

      - name: No changes detected
        if: steps.check_changes.outputs.changed == 'false'
        run: echo "No submodule updates found"
